"""
Django settings for justchat project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from tweepy import OAuthHandler
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^*8n!*tlfl1t094&hx(knk_ylv8qy24+f2mx1oaz(8+6bq%^j='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'channels',
    'chat',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'justchat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'justchat.wsgi.application'
ASGI_APPLICATION = 'justchat.routing.application'

TWEEPY_CREDS = {
  'consumer_token': 'YENNw3iHxHq8IQsovWmtmmliV',
  'consumer_secret': 'gYioxESc8UMNTay8JkiQAhuwQjs7oLZjLeg9rx2ofU0XKNs54F',
  'access_token': '1199041951-99lHNaNFS1U1cVCbmAL4HRQIcvQ0NfmpL9tM1Kk',
  'access_secret': 'n4TxMMK55WGqj5JhUSMhu9H93AKnaE9D7wCShgsK3Ih4q'
}

TWEEPY_AUTH = OAuthHandler(TWEEPY_CREDS.get('consumer_token'), TWEEPY_CREDS.get('consumer_secret'))
TWEEPY_AUTH.set_access_token(TWEEPY_CREDS.get('access_token'), TWEEPY_CREDS.get('access_secret'))

# mysite/settings.py
# Channels

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}
# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

TWEEPY_CREDS = {
  'consumer_token': 'XxBGGkJJpB87uwiy5iDghq7Vg',
  'consumer_secret': 'mS8JiaxIhd44LNb1QWuYthcC6rNHVC5yc7V0zX18qpCcySPgY6',
  'access_token': '248714285-mJiDC9ji7ttPX5fSYG8vPHHcjtJn1gTP5nyh6JqV',
  'access_secret': '9d0XEJ0ib4CZlWZ2wTWIKqPnmzHbcqqIDOelim65PFNDV'
}

TWEEPY_AUTH = OAuthHandler(TWEEPY_CREDS.get('consumer_token'), TWEEPY_CREDS.get('consumer_secret'))
TWEEPY_AUTH.set_access_token(TWEEPY_CREDS.get('access_token'), TWEEPY_CREDS.get('access_secret'))

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
